const express = require("express");
const app = express();
const serverless = require('serverless-http');

// Serve static files from the 'build' folder generated by CRACO
app.use(express.static("build"));

const PORT = 3000;
app.listen(PORT, () => {
  console.log(`Server is running on port ${PORT}`);
});

module.exports.handler = serverless(app);
module.exports.APP = app;


