const express = require("express");
const app = express();

const BLOCKED_COUNTRY = "US";

function geoblocker(req, res, next) {
  if (!req.geo || !req.geo.country) return next();

  const country = req.geo.country;

  const pathname = req.path;

  if (pathname === "/unavailable") {
    if (country === BLOCKED_COUNTRY) {
      return next();
    }
    return res.redirect("/");
  }

  if (country === BLOCKED_COUNTRY) {
    return res.redirect("/unavailable");
  }
}


app.use(geoblocker);

// Serve static files from the 'build' folder generated by CRACO
app.use(express.static("build"));

// Send index.html for any other requests
 app.get('*', (req, res) => {
   res.sendFile(__dirname + '/build/index.html');
  });

const PORT = 3000; //TODOX
app.listen(PORT, () => {
  console.log(`Server is running on port ${PORT}`);
});

