export const languages = {
    text_title1: 'This warmup release starts at 1% return and small TVL',
    text_title2: 'while we warm up our placement channels and improve reliability',
    text_sweep_title: 'SWEEP Metrics',
    text_sweepr_title: 'SWEEPR Metrics',
    text_assets_title: 'Assets',
    text_page_not_found: 'Page Not Found',
    text_bridge: 'Bridge',
    text_change_network: 'You should change the network to the ',
    text_tx_process: 'Transaction is in progress.',
    text_tx_success: 'Success: Transaction is completed.',
    text_tx_error: 'Transaction cancelled by user.',
    text_empty_asset: 'No SWEEP assets on selected chain.',
    text_buy_sweep: 'Buy from MarketMaker',
    text_copyright: 'Copyright © 2023 Sweep Protocol',

    label_current_supply: 'Local/Total Supply',
    label_sweep_total: 'SWEEP Total',
    label_sweepr_total: 'Sweepr Total',
    label_sweep_local: 'SWEEP Local',
    label_sweepr_local: 'SWEEPR Local',
    label_interest_rate: 'Interest Rate',
    label_target_price: 'Target Price',
    label_amm_price: 'AMM Price',
    label_balance: 'Balance: ',
    label_transfer_from: 'Transfer From: ',
    label_transfer_to: 'Transfer To: ',
    label_buy_from: 'Spend: ',
    label_buy_to: 'Get: ',

    column_name: 'Name',
    column_borrowed: 'Borrowed',
    column_limit: 'Limit',
    column_value: 'Value',
    column_min_equity: 'Min.Equity',
    column_equity: 'Equity',
    column_status: 'Status',
    column_call_time: 'Call Time',
    column_call_delay: 'Call Delay',
    column_call_amount: 'Call Amount',

    link_deal: 'Deal Page',
    link_borrower: 'Borrower Activity',
    link_stabilizer: 'Stabilizer Contract',
    link_go_home: 'Go Home',

    btn_link_uniswap: 'Sweep on Uniswap for',
    btn_buy_sweep_on_market: 'Buy at',
    btn_sweep_bridge: 'Sweep Bridge',
    btn_sweepr_bridge: 'Sweepr Bridge',
    btn_send: 'Send',
    btn_buy: 'Buy',
    btn_close: 'Close',
    btn_approve: 'Approve',
    btn_pending: 'Pending ...',
    btn_connect: 'Connect Wallet',
    btn_change_network: 'Change NetWork'
}